- auto_rx/auto_rx.py
- auto_rx/config_reader.py
- auto_rx/station.cfg.example
- auto_rx/utils/plot_rtl_power.py
- Fixed issues with rtlsdr_gain setting. Use a setting of -1 to get automatic gain control, otherwise specify the desired gain as a value in dB.
- Added the plot_rtl_power.py util in utils/ to assist with debugging these sorts of issues.
- Added a dwell_time parameter, which allows adjusting the time rs_detect sits on a frequency and tries to detect a sonde. Allows for speeding up scanning quite considerably. Needs more testing to determine a suitable default value.
- Added detection of OSX OS, which removes the '-k 30' option from the rtl_power call, as this isn't supported under the macports-provided timeout command. May need to look at a better way of handling this.
- Made the -f option quit if no sonde is detected on the supplied frequency.
> RTLSDR Gain Fixes & Other updates.

- auto_rx/auto_rx.py
rtl_fm appears to have significantly degraded performance when used in fixed-RX-gain mode (i.e. anything other than automatic RTLSDR gain). 
The use of the -F9 parameter (improved decimation filters) appears to reverse this degraded performance (~15-20dB performance increase!), possibly due to additional AGC action occurring within the FM demodulator.
This change adds the -F9 option to all calls to rtl_fm.
Additional changes include:
- Addition of an 'uber debug' feature, which copies the output of every rtl_power run to the log directory - this is incredibly useful for debugging sonde detection issues, though does result in a whole bunch of log data being written.
> Add use of rtl_fm -F9 parameter

- auto_rx/auto_rx.py
- auto_rx/config_reader.py
- auto_rx/station.cfg.example
This change add in support for the user to supply the following frequency lists:
- White-List: Only scan on these supplied frequencies.
- Black-List: Remove the supplied frequencies from the list of detected peaks (i.e. to remove known spurs)
- Grey-List: Add the supplied frequencies to the start of each scan list, so they are checked prior to looking at other frequencies.
I've also removed the 'highpass 20' option from the RS41 demod call, as it appears to degrade performance.
> Add White/Black/Grey-list functionality.

- auto_rx/auto_rx.py
- auto_rx/config_reader.py
- auto_rx/station.cfg.example
Add two position filtering options:
- Altitude cap - this will stop the payload jumping to absurd altitude when the GPS position glitches out.
- Radius cap - same as above, but based on radius from the station lat/lon (if set).
> Add position filtering, based on altitude and/or radius from listener.

- auto_rx/auto_rx.py
- auto_rx/station.cfg.example
- demod/rs41dm_dft.c
- demod/rs92dm.c
Add support for reading RS41 temperature values. 
Added better RS92 error checking.
These can be added to the APRS comment using the <temp> field.
If no temperature data is available, the field is set to -273 degrees C.
> RS41 Temperature Support

- auto_rx/auto_rx.py
- auto_rx/config_reader.py
- auto_rx/habitat_utils.py
- auto_rx/station.cfg.example
This creates a new payload document per radiosonde based off the serial number. This has been tested with RS41 but not the RS92
Fixes #32
> Add callsign per sonde option for habhub

- auto_rx/auto_rx.py
- auto_rx/config_reader.py
- auto_rx/station.cfg.example
Adds optional support for dumping sonde packets to a MQTT server. Uses `paho-mqtt` library but it isn't imported unless it is enabled in the config, so you won't need to install it if you're not using it.
> MQTT support

- auto_rx/auto_rx.py
- auto_rx/config_reader.py
- auto_rx/station.cfg.example
- APRS Server selection in config file.
- Add options for paths to rtl_fm and rtl_power to the config file. This will allow for further experimentation with the rx_tools utilities (once a few issues have been resolved).
- Stop APRS packets being uploaded if the radiosonde has no GPS lock.
- Some re-structuring of the config file.
> Multiple Updates - APRS Server Selection + some preliminary work to allow experiments with other RX utilities

- auto_rx/auto_rx.py
Implements #50 
Seemed to work OK for RS_N4810433 this afternoon
Note that function  initPayloadDoc uses the variable name "serial" internally for what is no longer strictly the serial number. Let me know if you'd like the pull request updated with that changed to e.g. payload_callsign
> Prepend RS_ to habitat payload name/callsign

- auto_rx/auto_rx.py
- auto_rx/config_reader.py
This PR adds the following:
- Check the payload ID (serial number) against a regex based on Vaisala serial number datasheets. The regex used is: [J-T][0-5][\d][1-7]\d{4}
- Maintain a list of observed payload IDs, and only permit uploading to web services (Habitat, APRS), if a particular ID has been observed more than 5 times. This value is based on observed occurrences of corrupted payload IDs.
> Added regex-based payload ID filtering, and payload validity checks.

- auto_rx/auto_rx.py
- auto_rx/gps_grabber.py
- auto_rx/habitat_utils.py
This PR does the following:
- Replaces all urllib2/httplib calls with calls to requests - brings us a bit closer to Python 3 support.
- Adds checking for the current sonde callsign on the tracker before creating a new payload document. This will hopefully help avoid the creation of multiple documents for the one payload.
- Some better logging around scanning when a blacklist is used.
> Remove urllib2/httplib dependencies, other updates.

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
Fixed an issue where older Vaisala RS92s (Pre-~2015 or so) were being detected as invalid serial numbers.
I'm also pre-emptively adding support for RS41s manufactured after 2021. Thinking ahead :-)
> Add support for older/newer vaisala serial numbers.

- auto_rx/autorx/__init__.py
- auto_rx/autorx/habitat.py
- auto_rx/autorx/ozimux.py
- Fix sending of UDP broadcast messages when there is no network connection (send to localhost instead).
- Add automated uploading of Habitat station position every 6 hours, if no sondes are observed.
> UDP Broadcast Fixes, Regular Habitat station position updates.

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/habitat.py
- auto_rx/autorx/rotator.py
- auto_rx/station.cfg.example
This PR re-adds rotator control, which has been missing since the code re-structure.
It's been tested on a real (SPID Rot2Prog) rotator controller, but doesn't seem to work correctly with rotctld's 'Dummy Rotator' endpoint (which just returns RPRT -1 to all commands?).
It would be good to have this tested on other rotator controllers, but that's not really something I can do myself.
> Rotator Control (via rotctld)

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/web.py
Small pull request to temporarily fix https://github.com/projecthorus/radiosonde_auto_rx/issues/98
Really needs testing by someone that has gevent installed to ensure the forcing of werkzeug works.
> Use werkzeug by default, suppress any gevent messages.

- m10/M10Decoder.cpp
Fixed a typo and some necessary allocation to avoid errors on deleting M10Decoder object before everything is allocated
Tested & working on windows and linux using the build.sh script.
> Fixed error if -h

- auto_rx/autorx/__init__.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/utils.py
- auto_rx/build.sh
- auto_rx/test/README.md
- auto_rx/test/generate_lowsnr.py
- auto_rx/test/test_demod.py
- demod/demod_dft.c
- demod/demod_dft.h
- demod/demod_iq.c
- demod/demod_iq.h
- demod/dfm09dm_dft.c
- demod/m10dm_dft.c
- demod/rs41dm_dft.c
- demod/rs41dm_iq.c
- scan/dft_detect.c
This PR switches auto_rx to using dft_detect. While we haven't really checked the performance differences when using rtl_fm, tests using csdr as a FM demodulator show significantly improved detection performance, and no issues with mis-detections.
> Switch to dft_detect for scanning.

- auto_rx/autorx/__init__.py
- auto_rx/build.sh
- auto_rx/test/test_demod.py
- scan/dft_detect.c
~3x speedup, no change in detection performance.
Comparison of pre-update and post-update performance follows:
Old dft_detect
--------------
dfm09_96k_float_10.0dB.bin, error
Runtime: 27
dfm09_96k_float_10.5dB.bin, error
Runtime: 27
dfm09_96k_float_11.0dB.bin, error
Runtime: 27
dfm09_96k_float_11.5dB.bin, error
Runtime: 27
dfm09_96k_float_12.0dB.bin, error
Runtime: 27
dfm09_96k_float_12.5dB.bin, error
Runtime: 27
dfm09_96k_float_13.0dB.bin, error
Runtime: 27
dfm09_96k_float_13.5dB.bin, error
Runtime: 27
dfm09_96k_float_14.0dB.bin, error
Runtime: 27
dfm09_96k_float_14.5dB.bin, error
Runtime: 27
dfm09_96k_float_15.0dB.bin, error
Runtime: 27
dfm09_96k_float_15.5dB.bin, DFM9: 0.6543
Runtime: 17
dfm09_96k_float_16.0dB.bin, DFM9: 0.6741
Runtime: 5
dfm09_96k_float_16.5dB.bin, DFM9: 0.6530 …
> Speedups to dft_detect

- m10/M10GtopParser.cpp
- m10/M10TrimbleParser.cpp
- m10/M10TrimbleParser.h
This is a PR to add the satellites number and the battery level to M10 Trimbles (or new GPS chip but same modulation), I added them as "satellites" and "battery" in the json.
I'm open for critiques for the names but I think we should uniformize theses names as they are both useful for RS hunting, the GPS number can tell us how precise the position emitted by the RS is and the battery level tells us if everything is OK and the RS will continue emit for a while.
We could send theses infos in the comments, maybe not each frame but once a while.
> GPS satellites number and battery level

- auto_rx/auto_rx.py
- auto_rx/auto_rx.service
- scan/dft_detect.c
- systemd service restart time increased to 120 seconds (from 3 seconds)
- Don't produce a system log (log/<timestamp>_system.log) by default. --systemlog command-line flag added to re-enable it (should we add a config option for this?)
- Update to latest dft_detect - no performahce changes noted, but it does add the -c and -t options, which may be useful (-t will do away with needing to kill rtl_fm using timeout).
> Update to latest dft_detect, fix log file and systemd restart issues.

- auto_rx/autorx/decode.py
- auto_rx/autorx/scan.py
- auto_rx/test/generate_lowsnr.py
- auto_rx/test/test_demod.py
What it says on the tin.
This is required to support RS92-NGPs (1680 MHz version of RS92). Unknown impact to other 1680 MHz sondes, though AFAIK there aren't many of these. 
The cutover frequency for changing receiver bandwidth has been set to 1 GHz.
> Use a wider FM bandwidth when scanning/decoding at 1680 MHz.

- auto_rx/autorx/scan.py
- auto_rx/autorx/utils.py
- demod/rs41dm_dft.c
- Fix trailing comma bug in burst timer json output.
- Add periodic checks of the scanner RTLSDR when in whitelist mode. Interim solution until we find a better way of checking for RTLSDR locks while running the detector.
> Whitelist and Burst Timer Fixes

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/sonde_specific.py
- auto_rx/autorx/utils.py
- auto_rx/test/generate_lowsnr.py
- auto_rx/test/test_demod.py
- imet/imet1rs_dft.c
Adds initial support for iMet sondes.
The iMet sonde 'id' is determined based on a SHA256 hash of the power-on time (determined from the current time and frame number) and the transmit frequency.
Decode performance is expected to be 7-8 dB (in Eb/N0) worse than other sonde types due to the AFSK modulation. 
TODO:
- Add configuration option to include a custom 'location' field, which can be used to add additional entropy to the sonde id hash, and hence better differentiate multiple iMet sondes. We'll see how we go without it for now.
> Initial iMet-4 Support

- auto_rx/auto_rx.py
- auto_rx/autorx/config.py
- auto_rx/station.cfg.example
Useful for listening on IPv6 or restricting to a particular address.
I use it set to :: to bind to all IPv6 addresses (on Linux this also listens on IPv4) and have done some limited testing of the default configuration which should still bind to all IPv4 addresses.
> Add web server host setting to config

- auto_rx/auto_rx.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/station.cfg.example
rs1729's comment here (https://github.com/projecthorus/radiosonde_auto_rx/issues/94#issuecomment-473624360 ) raises some scary possibilities if one of these sondes is encountered with the current iMet ID generation system.
This PR changes the logic to latch in the serial number on the first packet received, which will reduce the impact to the mapping systems. We'll still end up with multiple users generating different IDs, but at least we won't generate a new ID for every single new packet (!!).
This will unfortunately break support of multiple iMet sondes on a single frequency. I don't really see an alternative solution at this point.
> Latch iMet serial numbers to avoid issues with iMet-1-RS units.

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/email_notification.py
- auto_rx/autorx/scan.py
- auto_rx/station.cfg.example
This will fix https://github.com/projecthorus/radiosonde_auto_rx/issues/148 (requested by VK0HZ). 
It also adds some debugging features which allow the logging of the FM demodulated audio during the detection and decode steps. Note that this can result in very large audio files saved to disk, possibly reducing SD card life. I'm going to consider this addition to close https://github.com/projecthorus/radiosonde_auto_rx/issues/85.
Finally, I've removed some of the try/except blocks from the configuration parser. Users will need to make sure their station.cfg is up-to-date with the example.
> Add custom email subject field, add audio / IQ logging options.

- auto_rx/auto_rx.py
- auto_rx/autorx/utils.py
Basic check of the current master version on startup. Currently not showing any warnings if it's different, just reporting the local and current master version.
> Add version check on startup.

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/utils.py
- auto_rx/build.sh
- auto_rx/station.cfg.example
- auto_rx/test/test_demod.py
- demod/mod/bch_ecc_mod.c
- demod/mod/bch_ecc_mod.h
- demod/mod/demod_mod.c
- demod/mod/demod_mod.h
- demod/mod/dfm09mod.c
- demod/mod/lms6mod.c
- demod/mod/m10mod.c
- demod/mod/nav_gps_vel.c
- demod/mod/rs41mod.c
- demod/mod/rs92mod.c
- demod/rs41dm_dft.c
This PR updates the RS41 and RS92 decoders to the latest ['modular' decoders ](https://github.com/rs1729/RS/tree/master/demod/mod) from rs1729's repository. Updates in these decoders includes:
- Preliminary RS41 humidity calculation support.
- Better handling of RS41-SGM telemetry (a 'encrypted' flag is added to the JSON output).
In the auto_rx repo, this PR adds a temporary blocklist function, which will block the frequency of a RS41-SGM for ~60 minutes, to avoid continuous detection and lock-on of an encrypted radiosonde.
> Decoder updates, better handling of encrypted RS41s.

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
Fix a type when handling RS41-SGM sondes which was causing auto_rx to crash out.
> Fix bug with RS41-SGM handling.

- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/test/README.md
- auto_rx/test/generate_lowsnr.py
- auto_rx/test/test_demod.py
- demod/mod/dfm09mod.c
- Update to latest dfm09mod from RS repo, fixes issues with some DFM09 sondes not obtaining an ID.
- Change DFM APRS callsign format so it matches dxlAPRS.
> DFM09 Fixes, DFM APRS callsign change.

- auto_rx/autorx/logger.py
Without this, Python 3.7.3 is throwing the following error after a pop:
```
RuntimeError: dictionary changed size during iteration
```
> Iterate over a copy of the dictionary

- auto_rx/auto_rx.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/web.py
Followup to https://github.com/projecthorus/radiosonde_auto_rx/pull/210, with the aim of proactively dealing with other occurances where a `pop` will cause a dictionary to be modified while being iterated over.
As far as I know I hadn't experienced any issues with any of these yet, but it may just be I haven't exercised the relevant code-paths in my simple usage so far. With that in mind, these changes should be assumed to be untested.
> Iterate over a copy of the dictionary (2nd instalment)

- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/fsk_demod.py
- auto_rx/autorx/habitat.py
- auto_rx/build.sh
- auto_rx/station.cfg.example
- auto_rx/test/bit_to_samples.py
- auto_rx/utils/plot_sonde_log.py
- demod/mod/demod_mod.c
- demod/mod/demod_mod.h
- demod/mod/dfm09mod.c
- demod/mod/lms6Xmod.c
- demod/mod/lms6mod.c
- demod/mod/m10mod.c
- demod/mod/meisei100mod.c
- demod/mod/rs41mod.c
- m10/M10TrimbleParser.cpp
- Remove station_code from config file. Just use the default of SONDE.
- Fix bit_to_samples operation under Python 3.7 (it was broken, but in a 'silent' way, which means the experimental demod would not work correctly under Python 3)
- Remove -T (Trimble vs GTop) part from M10 serial number.
- Update all decoders to latest upstream version.
> Decoder rebase, few other fixes.

- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/habitat.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/utils.py
- auto_rx/build.sh
- auto_rx/test/test_demod.py
- demod/mod/demod_mod.c
- demod/mod/demod_mod.h
- demod/mod/dfm09mod.c
- demod/mod/lms6Xmod.c
- demod/mod/m10mod.c
- demod/mod/meisei100mod.c
- demod/mod/rs41mod.c
- demod/mod/rs92mod.c
- imet/imet1rs_dft.c
- scan/dft_detect.c
Lots of changes here.
- dft_detect IQ input (48 kHz BW from rtl_fm) is now used by default for 400 MHz sondes, and for 1680 MHz RS92s. Wide FM demod is still used for LMS6-1680 sondes. The IF bandwidth for dft_detect has been tweaked to achieve similar performance to the 22 kHz FM demod approach, but still work OK up to +/- 5 kHz frequency offset for 400 MHz sondes. A sider 32 kHz IF bandwidth is used for RS92-NGP sondes.
- Changed to m10mod, using the new APRS ID.
- The frequency provided in the Habitat sentence comment now uses the frequency offset information from fsk_demod, if it is available.
> Decoder Rebase, Switch to m10mod, dft_detect IQ input

- Dockerfile
Works around an issue with piping stdin in to `fsk_demod`, which only surfaces when built using `musl`. This prevents the effective use of the experimental decoders.
Alpine Linux uses `musl`, whereas Debian uses `glibc`, which doesn't appear to suffer from this issue, hence the shift to Debian.
The hope is this will be temporary, and that we'll be able to return to Alpine Linux in the future, as a Debian based container is far larger than an Alpine Linux based counterpart. 
Efforts to understand why this is an issue, and ideally a fix, are ongoing, with @darksidelemm and I having spent quite a bit of time on this already.
> Migrate Docker Container from Alpine to Debian

- Dockerfile
Reduces the size of the resulting container from 488 MB down to 175 MB.
> Use a Docker Build Container

- auto_rx/station.cfg.example
Left me confused for a while why I couldn't get it to connect to a remote GPSD instance 😄
> station.cfg.example: s/gpsd_hostname/gpsd_host/

- Dockerfile
Ensures that `simplekml` is installed.
> Docker: Use requirements.txt for additional packages

- Dockerfile
Switches to using [Tini](https://github.com/krallin/tini) as the `init` for the Docker container, which should help with zombie processes (it isn't unusual to end up with a couple of `rtl_fm`, `fsk_demod` etc zombies a day).
> Docker: Use Tini as init

- auto_rx/build.sh
Enable compilation optimisations for everything. Roughly 50% speedup. 
Doesn't affect much as everything was running faster than realtime on a RPi 3, but might help on slower, or shared systems.
> O3 all the things.

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/gps.py
- auto_rx/autorx/sondehub.py
- auto_rx/station.cfg.example
This PR adds a new 'Sondehub DB' uploader. This is separate to the Habitat database, and *all* received telemetry is uploaded (gzip compressed to reduce upload size).
We hope to eventually enable better radiosonde telemetry access services via this new database.
For now, the upload rate and user position / antenna metadata is tied to the Habitat uploader settings. Eventually these will be separated, and we may move to a more real-time websockets based uploader.
> Add upload of all telemetry to Beta Sondehub DB

- auto_rx/build.sh
On Debian systems with only Python 3 installed, the `python` command is not available, and `python3` must be used instead.
This PR updates the logic to try `python3` first, and if not available, then fall back to trying `python`, which generally points at Python 2 if installed.
> Version detection: Use Python 3 if available

- .github/dependabot.yml
- .github/workflows/container.yml
- Dockerfile
- auto_rx/requirements.txt
1. Overhauls the `Dockerfile`.
2. Introduces a basic GItHub Actions Workflow to build Images for `amd64`, `386`, `arm64`, `armv6`, and `armv7` architectures. This will help identify changes within in the wider project that break the container build process.
3. Activates GitHub Dependabot for Actions Workflows so that PRs are automatically created when updates to the upstream Actions occur.
I am hoping to open another PR soon that expands this GitHub Actions Workflow so that it publishes these Container Images to a Container Registry automatically for consumption so that users do not have to `docker build` these themselves. I am near the finish on this, but wanted to split these out as two separate PRs.
> Container Updates

- auto_rx/autorx/__init__.py
- mrz/mp3h1.c
The MRZ decoders serial number record now 'times out' after 60 seconds, which will help avoid issues with stations listening constantly on a single frequency.
> Update MRZ decoder.

- .github/workflows/container.yml
Pushes the built container images up to GitHub Container Registry.
Will automatically push `testing` whenever that branch changes, as well as each release whenever a new tag is created, with the latest release also being available at `latest`.
> Push container images

- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/templates/index.html
I have solved an edge case where if the page is loaded on a low-resolution (720p) monitor the table is too large so it will default to the mobile view in this case.
I have added support for displaying Imperial units which solves #383 (when the setting is applied the page is refreshed as this is the only way I could find to update table headers).
I have also implemented a down icon if the settings menu can be scrolled.
Please check that these features all work as expected.
Thanks
> Website: Imperial units, down indicator, default table view

- auto_rx/autorx/templates/index.html
I have added an option to hide the version number (disabled by default), update available messages will still be shown.
When the version number is longer then screen width the entire string will be shown on new line (doesn't waste any vertical space and looks better).
> Mobile version display fixes.

- auto_rx/autorx/templates/index.html
This is a bit more of a personal preference change but I don't believe it negatively impacts anything.
I like to look at the changes with each testing beta version and as no changelog is provided I believe linking to the commit history is best.
> Change Update Link if beta release

- auto_rx/autorx/templates/index.html
This changes the pan duration to just over 1 second which is the interval between most sonde frames and changes the panning to be more linear so that when following a sonde the movement feels smooth.
> Make following a radiosonde on the map buttery smooth

- auto_rx/autorx/static/css/main.css
This is the workaround discussed in this leaflet issue to make the grid lines disappear on high DPI monitors. While it doesn't resolve the issue fully, it is MUCH better
https://github.com/Leaflet/Leaflet/issues/3575#issuecomment-688644225
**Before**
**After**
> Hack around subpixel issue to make it less noticeable

- Dockerfile
Useful for remote development. Only adds ~45kB to the image size.
> Include libatomic1 in the container

- auto_rx/autorx/utils.py
- auto_rx/requirements.txt
Resolves the issue where `1.5.2` for example was not considered newer than `1.5.2-beta6`.
Non Docker users will need to install the `semver` Python package (`requirements.txt` can be used for this).
> Use semver for version comparisons

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/log_files.py
- auto_rx/autorx/sondehub.py
- auto_rx/autorx/utils.py
- auto_rx/autorx/web.py
Adds a /get_log_list endpoint, which returns a list (as JSON) of the form:
```
[{"datetime": "2021-05-09T00:48:17Z", "age": "1 hours 9 minutes", "serial": "S2510446", "type": "Vaisala RS41", "freq": 401.501}, {"datetime": "2021-05-08T23:02:31Z", "age": "2 hours 55 minutes", "serial": "S4631583", "type": "Vaisala RS41", "freq": 401.5}, {"datetime": "2021-05-08T11:07:25Z", "age": "14 hours 50 minutes", "serial": "S4631584", "type": "Vaisala RS41", "freq": 401.501}, {"datetime": "2021-05-08T00:58:36Z", "age": "1 days 59 minutes", "serial": "S2510449", "type": "Vaisala RS41", "freq": 401.5}, {"datetime": "2021-05-07T23:02:01Z", "age": "1 days 2 hours 56 minutes", "serial": "S4631619", "type": "Vaisala RS41", "freq": 401.5}, {"datetime": "2021-05-07T10:21:41Z", "age": "1 days 15 hours 36 …
```
> Add starts of log archive endpoints, so web development can be started

- Dockerfile
- Dockerfile.dev
- auto_rx/requirements.txt
Initial testing on a Pi Zero W seems to indicate that this solves the NumPy issue.
> Docker: Use Debian's Slim Buster as the base for the container image

- Dockerfile
While this hasn't been a problem so far, to be safe we should use `--ignore-installed` to ensure that everything we need ends up in `/root/.local` ready to be copied over to the final container.
The risk if we don't is that a dependency of `python3-pip` will be used, but then not available in the final container.
> Docker: Install all dependencies using pip

- auto_rx/autorx/__init__.py
- auto_rx/autorx/utils.py
Instead of checking `semver.compare` is `True`, which simply indicates if the versions are different, we should be checking that `semver.compare` is `1`, which indicates that the version we are comparing against is newer than the local version.
This is mainly to prevent messages indicating a newer version is available when running a release candidate.
> Alert on newer, not different

- Dockerfile
- Dockerfile.dev
Debian 11 (Bullseye) has been released now, so updating the container images to use this as the base.
Some initial local testing has so far went well, but figured it would be good to get this in `testing` early on in the 1.5.6 development cycle so we can put it through its paces more before releasing 1.5.6.
> Docker: Use Debian Bullseye as the base

- Dockerfile
- Dockerfile.dev
Reverts projecthorus/radiosonde_auto_rx#562
Received a report of https://github.com/moby/moby/issues/40734 suddenly being triggered by the move from Buster to Bullseye. Reverting for now until I can figure out what is going on.
> Revert "Use debian bullseye as the base"

- utils/fsk_demod.c
Doing a `fflush` on `stdin` was preventing `fsk_demod` from functioning on Alpine Linux, which uses musl libc (https://wiki.musl-libc.org/functional-differences-from-glibc.html).
My understanding is that `fflush` is generally used for clearing the output stream, and when used on input streams is only really usable for seekable files, so in most cases is ineffective when used with `stdin`.  I'm not sure what the purpose of flushing `stdin` was here?
Also noticed it was alternatively checking for `fout == stdin`, which in theory should never be the case.
In my limited testing this fixed the issues I experienced on Alpine Linux with no obvious negative impact to glibc environments, though I lack context as to why it was the way it was, so may be missing something.
/cc @drowe67
> Flush stdout only

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/station.cfg.example
> Restrict allowed APRS servers and ports.

- auto_rx/auto_rx.py
- auto_rx/autorx/config.py
- auto_rx/autorx/email_notification.py
- auto_rx/station.cfg.example
Useful for those who own more stations, they can add station name to nearby_landing_subject field in station.cfg
> Custom nearby landing email subject

- auto_rx/utils/receiver_stats.py
I was reading through the logic that calculates the distance and elevation because I was curious about whether it properly treated the earth as spherical. Happily, it does.
However, I noticed that the distance calculation was excessively complex. Simple algebra shows that my formula is the same.
We have: 
```
ea = (cos(angle_at_centre) * tb) - ta
eb = sin(angle_at_centre) * tb
```
Therefore if we square each one:
```
ea**2 = cos(angle_at_centre)**2 * tb**2 + ta**2 - 2*cos(angle_at_centre)*tb*ta
eb**2 = sin(angle_at_centre)**2 * tb**2
```
Add them together and factor out the tb**2 term at the start of each:
```
ea**2 + eb**2 = tb**2 * (cos(angle_at_centre)**2 + sin(angle_at_centre)**2) + ta**2 - 2*cos(angle_at_centre)*tb*ta
```
Of course a basic trigonometric identity is that summing the …
> Simplified distance formula

- Makefile
I have measured the `fsk_demod` and with clang 11 and gcc 10 the clang is ~15% faster
> Allow compiler selection

- demod/mod/Makefile
- utils/Makefile
The dependencies were added manually. This can be automated with some more advanced `Makefile` magic, but I'm not sure it's worth the complexity in such a simple case.
> Makefile: add build dependencies for header files

- auto_rx/autorx/templates/index.html
For low elevation angles (eg 0.9°) the second decimal place rally matters, with only one the occuracy is rapidly decreasing.
> Show more decimals for low elevation angles

- auto_rx/autorx/sdr_wrappers.py
This reduces overhead and removes unnecesary string spliting and joining
> Load rtp_power output directly from string

- auto_rx/autorx/config.py
When any of those options is missing the sdr_type is overwriten to RTLSDR. But this is confusing because it hides the real error and causes unexpected behaviour.
> Keep sdr_type set and do not override to RTLSDR when some opts are missing

- auto_rx/autorx/decode.py
- auto_rx/autorx/scan.py
- auto_rx/utils/log_to_kml.py
The * imports also all other objects imported by the module, which easily leads to a mess and hard to find issues, especially during development.
> Replace import * by importing only required objects

- auto_rx/autorx/decode.py
This somehow slipped of, during the refactors.
> Add missing import of get_sdr_name

- auto_rx/autorx/__init__.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/sdr_wrappers.py
- auto_rx/autorx/utils.py
- auto_rx/build.sh
- auto_rx/clean.sh
- demod/mod/Makefile
- demod/mod/iq_dec.c
Add in a DC block stage into the IQ processing chain.
This helps remove the residual DC offset which seems to be present in the output of both rtl_fm and ss_iq, likely just from quantization issues. 
From testing, this gives perhaps a 5dB decode improvement.
> Add DC block to IQ chain.

- auto_rx/autorx/templates/index.html
I use beta25.
When I receive MEISEI iMS-100, the ID of main screen contain 'IMS100-'.
So I modified it which follows DFM, M10, M20, IMET, IMET5, IMET54 and MRZ.
I have no issue in SondeList about ID of MEISEI.
Before this patch of main screen 
After this patch of main screen
> Remove MEISEI sonde type from  ID

- auto_rx/autorx/__init__.py
- auto_rx/requirements.txt
This should remove those pesky "The WebSocket transport is not available" messages...
> Add simple-websocket to requirements

- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/email_notification.py
Only send landing notifications if sonde has gone above the landing alt threshold first.
Allow APRS-IS to localhost.
> Landing notification tweaks, allow localhost APRS

- .gitignore
#735 added a new program (`iq_dec`) but did not add the executable to to the `.gitignore` file. I've done that here, which should prevent git from reporting it as an untracked file.
> Add iq_dec to .gitignore

- auto_rx/autorx/web.py
In the KML feed, Ascent Rate is currently displayed in scientific notation, which is difficult to read:
Here I've changed it to fixed-point to match the other fields:
> Use fixed-point notation for ascent rate

- auto_rx/autorx/web.py
While looking at web.py, I noticed that `flask_export_selected_log_files` and `flask_export_all_log_files` are almost identical. By combining them, some code duplication can be avoided.
> Combine export_selected and export_all

- auto_rx/autorx/log_files.py
- auto_rx/autorx/templates/historical.html
- auto_rx/autorx/web.py
- auto_rx/utils/log_to_kml.py
Log files can be converted to KML using the `log_to_kml` command-line utility. To make the process simpler, I've added a "Generate KML" button to the "Historical" page:
When clicked, a KML file is generated from the selected log files.
To avoid making `fastkml` and `shapely` dependencies of auto_rx, I rewrote `log_to_kml` to generate KML using the standard library's built-in XML support. (It should be possible to eliminate auto_rx's `simplekml` dependency in the same way, but I'll leave that to another pull request.)
> Generate KML files from the "Historical" page

- auto_rx/autorx/config.py
- auto_rx/autorx/log_files.py
- auto_rx/autorx/web.py
- auto_rx/requirements.txt
- auto_rx/utils/log_to_kml.py
Here I've switched live KML generation over to Python's built-in `ElementTree`, which allows it to share a lot of code with the `log_to_kml` utility and eliminates the dependency on `simplekml`. I also modified the output of `log_to_kml` a bit to make it more like live KML, which I think makes it a bit nicer to work with.
> Generate live KML using ElementTree

- auto_rx/auto_rx.py
When I used `auto_rx.sh` for testing, the 180-minute timeout caught me by surprise. I think it would be useful to log an informational message if a shutdown timeout is set.
> Log the shutdown timeout if set

- auto_rx/auto_rx.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/email_notification.py
- auto_rx/autorx/emulation.py
- auto_rx/autorx/gps.py
- auto_rx/autorx/logger.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/sonde_specific.py
- auto_rx/autorx/sondehub.py
- auto_rx/autorx/static/js/scan_chart.js
- auto_rx/autorx/web.py
- auto_rx/utils/listener_nmea_crlf.py
- auto_rx/utils/plot_sonde_log.py
As of Python 3.12, [`datetime.utcnow()` is deprecated](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow), with the recommended replacement being `datetime.now(timezone.utc)`. I made that replacement here. This was a simple search-and-replace, except in `listener_nmea_crlf.py` where I modified the code to be more like the other scripts. So far I haven't done much testing apart from firing up auto_rx.
> Replace deprecated utcnow() with now()

- auto_rx/autorx/static/js/scan_chart.js
#867 changed the format of the time displayed in the Scan Results section. The old format was nicer, so I changed the code back to the old version, and simplified it to work with the updated format coming from the Python side.
My system now displays:
2024-03-29, 11:59:26
or:
2024-03-29 16:04:06 UTC
> Restore the previous time format in Scan Results

- auto_rx/autorx/templates/index.html
If the scan chart is open prior to the first scan being completed, an uncaught error occurs:
```
Uncaught Error: Source data is missing a component at (0,1)!
convertColumnsToData http://localhost:5000/static/js/c3.min.js:2
loadFromArgs http://localhost:5000/static/js/c3.min.js:2
load http://localhost:5000/static/js/c3.min.js:2
redraw_scan_chart http://localhost:5000/static/js/scan_chart.js:80
<anonymous> http://localhost:5000/:213
jQuery 8
<anonymous> http://localhost:5000/:199
emit http://localhost:5000/static/js/socket.io.min.js:6
value http://localhost:5000/static/js/socket.io.min.js:6
value http://localhost:5000/static/js/socket.io.min.js:6
value http://localhost:5000/static/js/socket.io.min.js:6
value http://localhost:5000/static/js/socket.io.min.js:6
emit …
```
> Don't update scan chart data until there's actual data

- auto_rx/build.sh
This ensures script will not continue to build when error accures. Continuing the build after some part fails only brings more errors and makes the output harder to understand.
> auto_rx/build.sh: exit immediatelly on error

- auto_rx/autorx/__init__.py
- auto_rx/autorx/ka9q.py
- auto_rx/autorx/sdr_wrappers.py
Updates in ka9q-radio broke compatibility, as a command line option to pcmcat was removed.
> Fix KA9Q support to work with latest commit (2024-06-11, 26a8015)

- auto_rx/autorx/__init__.py
- auto_rx/autorx/decode.py
- utils/fsk_demod.c
Added an option to fsk_demod which will flip the sign of the output soft decisions.
This seems to make dfm09mod detect the DFM types correctly.
> Workaround for DFM detection issue. 

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/rotator.py
- auto_rx/autorx/sondehub.py
- auto_rx/station.cfg.example
- auto_rx/station.cfg.example.network
Send full-precision frequency estimator data to sondehub (We'll see how this goes... May still reduce precision a little). 
Also add azimuth_only option to the rotator settings, which will force elevation to 0.
> 1.7.5-beta4 - Increase precision of estimated frequency output, add rotator azimuth_only

- .github/workflows/container.yml
- Dockerfile
This will be especially helpful when iterating on a branch, when the versions of dependencies are unlikely to have changed significantly.
> Cache wheels for container builds

- .github/workflows/container.yml
This will both keep the wheel cache warm, as well as ensure that we don't have any breakages waiting for us do to upstream changes in dependencies.
For consistency, runs 4:25am on a Wednesday UTC. Time and day picked at random.
We won't see the full benefits of this caching until this makes it from `testing` to `master`.
> Automatic weekly build

- auto_rx/autorx/__init__.py
- demod/mod/imet54mod.c
Possibly fixing a sondehub ingestion bug.
> Change iMet54 subtype names

- auto_rx/autorx/__init__.py
- auto_rx/autorx/sondehub.py
202 responses from sondehub about payload data errors were being reported only as a debug message. This was originally because all the DFM z-check errors were making people nervous.
I've now taken the approach from horusdemodlib which breaks out each error into a separate log message. Messages relating to z-check are only reported as debug level, everything else is reported as an error.
> v1.7.5-beta7 - Better handling of error responses from Sondehub

- auto_rx/autorx/static/js/scan_chart.js
The X axis of the scan plot is unwieldy, with hundreds of tick marks and odd frequencies displayed:
Providing a fixed list of frequencies cleans things up nicely:
I included frequencies for both the 403 MHz and 1680 MHz bands. For the 1680 MHz band, I chose a 2 MHz spacing to avoid having too many labels when the full 1675-1700 MHz band is scanned.
> Put X axis ticks at exact MHz values

- auto_rx/auto_rx.py
- auto_rx/autorx/config.py
- auto_rx/autorx/ozimux.py
- auto_rx/station.cfg.example
- auto_rx/station.cfg.example.network
Still needs testing, I rarely get any sondes out there. Changed the emulation.py script locally to allow an OziUploader object and that worked, unsure about the configuration loading.
> Allow changing oziplotter and summary target host

- auto_rx/autorx/static/css/main.css
When the Historical page is opened, the map is not centered:
Closing the Sonde List sidebar also leaves the map uncentered, as does opening or closing the Log sidebar on the main page.
This happens because `mymap.invalidateSize()` is called immediately, but the left margin of the map moves for the next half second due to a CSS transition. The right margin does not have such a transition, and therefore doesn't suffer the same problem.
Removing the CSS transition solves the problem, and the map is then correctly centered in all cases.
> Remove transition from left margin of map

- auto_rx/autorx/log_files.py
After thousands of log files have accumulated, opening the Historical page becomes slow. A lot of the wait time comes from the `list_log_files` function, which scans the log files and summarizes them. I profiled this function and found that nearly half of the execution time is spent in `dateutil.parser.parse`, which is used to parse the time from the beginning of the log filename. I presume the `parse` function is slow because it must guess what time format has been used.
I tried switching to `datetime.datetime.strptime`, and this gave a significant speedup, but still a decent amount of time was spent in `strptime`, perhaps because it needs to parse the format string argument. Manually converting the pieces to integers and passing them directly into `datetime.datetime()` reduced the …
> Speed up log file processing

- auto_rx/autorx/log_files.py
- auto_rx/autorx/stats.py
- auto_rx/autorx/utils.py
- auto_rx/autorx/web.py
When viewing the Historical page over an internet connection, the time to load `/get_log_list` can be significant. By removing unused and redundant information, its size can be reduced by about 36%.
Here are the relevant changes:
* Remove JSON whitespace using `separators=(',', ':')`.
* Remove the `age` field, which is unused.
* Remove the `first.freq` and `last.freq` fields, which are unused and duplicate the `freq` field.
* Remove the `first.evelation` and `last.elevation` fields, which are only used by `stats.py`.
* Remove the `has_snr` field, which is only used by `stats.py`.
* Round `first.range_km`, `first.bearing`, `last.range_km`, and `last.bearing` to one decimal place.
Before:
`{"datetime": "2024-10-11T11:26:09Z", "age": "16 hours 56 minutes", "serial": "W2234350", "type": …
> Remove unused data from /get_log_list

- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/static/js/L.TileLayer.NoGap.js
- auto_rx/autorx/templates/historical.html
- auto_rx/autorx/templates/index.html
SondeHub uses [Leaflet.TileLayer.NoGap](https://github.com/Leaflet/Leaflet.TileLayer.NoGap) to eliminate gaps from Leaflet maps in WebKit-based browsers, and it seems to work well there. Also, it doesn't have the downside of blurring the map like the previous workaround did.
> Remove map tile gap workaround and use NoGap instead

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/rotator.py
- auto_rx/autorx/static/js/autorxapi.js
- auto_rx/autorx/templates/index.html
- auto_rx/autorx/web.py
This PR is to give more control of the rotator to improve the ability to receive one-off radiosondes that aren't otherwise captured in the usual scan process. Things that I have added/changed:
- Add az/el input to web GUI
- Add homing button to web GUI
- Allow manual steering when no radiosonde is being received
- Only move rotator on new telemetry
- Only home rotator once
The only part that I have doubts about (in terms of matching the auto_rx architecture) is the change to __init__.py by making a global rotator object. I'm all ears to a better way to achieve these things. 
EDIT: This is currently running on KE5GDB-QTH.
> Rotator Control Improvements

- auto_rx/autorx/ka9q.py
- auto_rx/autorx/sdr_wrappers.py
Spectrum scanning doesn't work properly with ka9q-radio because Auto-RX chooses the same RTP SSRC number (which ka9q-radio uses as a channel identifier) for both SDR tests and spectrum scanning. The SSRC value must be a unique 32-bit integer.
Here I've changed the SSRC generation to use the frequency in kHz (rounded to the nearest integer) followed by two digits to indicate the channel type (01 for sonde reception, 02 for SDR tests, 03 for spectrum scanning). I hope this will ensure the uniqueness of SSRC values.
> Ensure that SSRC values are unique

- auto_rx/autorx/sdr_wrappers.py
Auto-RX currently requests 7438.5 bins when running on an Airspy R2 with ka9q-radio. The powers utility expects this value to be an integer, so we should ensure that it is.
> Ensure number of requested bins is an integer

- auto_rx/autorx/ka9q.py
In #929 I forgot to update the code that generates the SSRC value for the pcmcat command, which breaks sonde reception. I've fixed that here.
> Fix SSRC generation for pcmcat command

- Dockerfile
ka9q-radio's makefile uses the `-march=native` option, which is only safe when running binaries on the same system they were built on:
https://github.com/ka9q/ka9q-radio/blob/770f988955a0dfb380b71d4cf58529cc6f824e67/Makefile.linux#L11
Overriding `COPTS` to remove this option should allow the binaries to be executed on other systems.
> Build ka9q utilities without -march=native

- auto_rx/autorx/templates/index.html
The `updateTelemetryTable` function can change the size of the telemetry table, which in turn changes the size of the map. (This occurs on startup when the table footer is hidden, and again whenever any new sondes appear.) But the function doesn't call `mymap.invalidateSize()`, which leaves the map incorrectly centered, at least on Firefox. (If the browser window is resized, then the map snaps back into place.)
Here I've added `mymap.invalidateSize()` to the end of the function. Although `updateTelemetryTable` is called frequently (at least once per second) I expect that this shouldn't cause performance problems because `invalidateSize` returns quickly if the map has not in fact changed size.
> Invalidate map size after updating telemetry table

- auto_rx/autorx/config.py
- auto_rx/autorx/sdr_wrappers.py
Auto-RX fails to start on the first attempt after a reboot, because the network does not come up within the 5-second timeout period of `test_sdr`. It then has to wait an extra two minutes before systemd restarts it.
I think it would make sense to increase the network timeout to 60 seconds (for both KA9Q and SpyServer) upon initial startup. This change works well on my system.
> Increase network timeout to 60 seconds on startup

- auto_rx/autorx/__init__.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/utils.py
The data sent to the web interface for the scan plot was being decimated 10x. This looked to be a decision made back in 2018, maybe for performance reasons.
After discussion with @argilo , I've decided to remove this decimation and allow the full resolution data to be seen in the scan plot.
Hopefully this doesn't lead to performance issues!
> Remove scan plot data decimation.

- auto_rx/autorx/sdr_wrappers.py
The `read_ka9q_power_log` function keeps the trailing newline character on each line it reads. Because ka9q-radio's "powers" utility ends lines with a trailing comma (proposed fix: https://github.com/ka9q/ka9q-radio/pull/65), `np.fromstring` interprets the trailing newline character as an invalid value and replaces it with -1. As a result, the list of bin powers is one too long, which causes the frequency range generated by `np.linspace` to be incorrect.
Here I've corrected the problem by removing the trailing newline with `rstrip()`. It is idiomatic to do this when reading lines from a file in Python. After this change, `np.fromstring` ignores powers' trailing comma.
I verified that this change works correctly with or without https://github.com/ka9q/ka9q-radio/pull/65.
> Remove trailing newline to ensure correct parsing

- auto_rx/autorx/sdr_wrappers.py
Fixes #938.
Forcing the C locale when running `powers` will prevent its CSV output from being corrupted.
This workaround can be removed once https://github.com/ka9q/ka9q-radio/pull/65 has been merged and enough time has passed that nobody is running buggy versions.
> Work around ka9q-radio powers locale bug

- auto_rx/autorx/static/js/scan_chart.js
By default, C3 charts have animated transitions when data is updated. This increases CPU utilization. We can probably do without it in Auto-RX.
> Turn off transition animations in scan chart

- auto_rx/autorx/static/js/autorxapi.js
This is a small first step towards making the tasking list smaller.
The "SDR:" prefix added to SDR names seems like it was only intended for RTL-SDR; it's omitted for SpyServer threads. Omitting it for KA9Q threads will save some space.
Before:
After:
> Don't prefix KA9Q threads with "SDR:"

- auto_rx/autorx/templates/index.html
When many sondes are displayed in the table, switching between pages can change the height of the table, which subsequently changes the height of the map. In this situation, `invalidateSize()` needs to be called to prevent the map from rendering incorrectly.
> Invalidate map size when switching to new table page

- Dockerfile
- auto_rx/autorx/ka9q.py
As noted in https://github.com/ka9q/ka9q-radio/issues/66, ka9q-radio recently changed pcmcat's behaviour with respect to network-to-host byte order conversions.
Previously, a network-to-host byte order conversion was always performed by default, and could be turned off with the `-b` flag.
Now, network-to-host byte order conversion only occurs by default for two specific RTP types (both having a sample rate of 44100, which Auto-RX does not use), and the `-b` argument takes a parameter: `-b 0` turns off network-to-host byte order conversion, while `-b 1` turns it on.
Because of the change to the `-b` argument, it would be impractical for Auto-RX to support both behaviours. Since Auto-RX expects samples in host byte order, explicitly requesting that with `-b 1` seems wise, even if it means …
> Explicitly request host byte order in pcmcat

- auto_rx/autorx/static/css/autorx.css
- auto_rx/autorx/static/js/autorxapi.js
- auto_rx/autorx/templates/index.html
When using ka9q-radio, the "Tasking" section takes up a lot of space:
Here I'm experimenting with a more compact display, with a circle representing each receiver:
* 🔵 = scanning
* 🟢 = receiving
* ⚪ = idle
Hovering over a circle shows the details in a tooltip:
Or click on the tasking section to display a list of all tasks:
> Use coloured icons for task status

- Dockerfile
This pulls in https://github.com/ka9q/ka9q-radio/pull/71, which gives a nicer-looking scan plot.
I am running this commit on my two stations without issue.
> Update to latest ka9q-radio commit

- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/static/js/scan_chart.js
- auto_rx/autorx/templates/index.html
The scan plot takes up quite a lot of precious vertical space. Here I've made it smaller by removing the "Scan Results" heading, reducing the vertical size from 320 pixels (the default) to 200 pixels, and removing the legend.
Before:
After:
> Reduce vertical size of scan plot

- auto_rx/autorx/static/js/scan_chart.js
If "Show Scan Plot" is toggled on before the first scan has completed, or the scan plot is open and the user navigates away from the Auto-RX tab and back before the first scan has completed, then an error occurs and the scan plot renders incorrectly:
This happens because `scan_chart_latest_timestamp` is not defined until the first scan has completed, but `redraw_scan_chart` (which is invoked when the scan chart is opened, or when the user navigates back from another tab) attempts to use it anyway.
To fix the problem, I've added a check so that `redraw_scan_chart` exits early if `scan_chart_latest_timestamp` is not yet defined.
> Don't redraw scan chart before first scan

- README.md
- auto_rx/autorx/__init__.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/ka9q.py
- auto_rx/autorx/sdr_wrappers.py
- auto_rx/station.cfg.example
- auto_rx/station.cfg.example.network
Some possible performance impacting changes in this one.
* get_sdr_iq_command function now accepts an optional channel_filter argument. This gets passed to the KA9Q channel setup, allowing bandpass filtering. We should look to see if this can be implemented for other SDR types.
* DC blocking is disabled for KA9Q setups. It doesn't look to be required. 
In response to an issue observed by @argilo where a DFM and RS41 are regularly seen only 10 kHz apart, I've made the following changes:
* RS41:
* Estimator range has been narrowed to +/- 5 kHz, and a +/- 5 kHz channel filter is enabled for KA9Q setups.
* fsk_demod is set to use a mask estimator, with a tone spacing of 4800 Hz.
* DFM:
* Estimator range has been narrowed to +/- 5 kHz, and a +/- 5 kHz channel filter is enabled for KA9Q setups. …
> v1.8.1-beta2 - KA9Q Channel Filter, RS41/DFM Estimator BW Tweaks

- Dockerfile
- auto_rx/autorx/ka9q.py
- auto_rx/autorx/sdr_wrappers.py
As noted in https://github.com/ka9q/ka9q-radio/issues/66#issuecomment-2552692572, @ka9q has merged pcmcat's functionality into pcmrecord, and pcmcat may be removed or converted to a shell script. Here I've switched over to using pcmrecord, and this is working well on my test station.
Since the required pcmrecord functionality is only available in recent commits, the wiki will need to be updated to recommend a newer commit. (I've tested with 08142683dbc398087a5b7d384b1a36bb24b1eca3).
Since a new commit is required, there's no reason to keep the workaround for the powers bug (#941) so I've reverted it here.
> Use pcmrecord instead of pcmcat

- auto_rx/autorx/__init__.py
- auto_rx/autorx/utils.py
- auto_rx/test/test_demod.py
With https://github.com/projecthorus/radiosonde_auto_rx/pull/971 merged in, we now required KA9Q-Radio commit 08142683dbc398087a5b7d384b1a36bb24b1eca3
> v1.8.1-beta4 - New KA9Q-Radio version required

- auto_rx/autorx/scan.py
Sonde detection fails in the presence of adjacent-channel interference from another sonde. This happens frequently at my receiving station, where launches from Buffalo, NY are heard on 403.800 MHz, and launches from Wilmington, OH are heard on 403.810 MHz. Narrowing the detection bandwidth to 15 kHz solves the problem.
This change also makes the exception for the RTL-SDR's 403.200 MHz spur unnecessary, so I have removed it.
> Narrow detection bandwidth to avoid adjacent-channel interference

- auto_rx/autorx/__init__.py
Detection bandwidth narrowed after testing from @argilo shows this resolved adjacent channel sonde issues.
> v1.8.1-beta5 - Narrowed detection bandwidth (20 kHz -> 15 kHz)

- .github/workflows/container.yml
Should workaround the random crashes during build on arm64. See https://github.com/tonistiigi/binfmt/issues/215.
> Use qemu8 for builds

- auto_rx/autorx/templates/index.html
The telemetry table often displays with a scrollbar when initially loaded, partially obscuring the final row:
Resizing the browser window causes the table to snap back to the correct height.
The problem occurs because the SondeHub and Radiosondy icons are not loaded until after the table is rendered. They are large enough to cause the table rows to expand. Adding explicit `height` and `width` attributes allows the browser to determine the final cell size before the images are loaded. The telemetry table then renders correctly on the initial page load:
> Specify image sizes in img tag

- Dockerfile
- auto_rx/autorx/__init__.py
- demod/mod/rs41mod.c
- Re-based RS41 decoder to latest from https://github.com/rs1729/RS
- Added in rdz_ttgo bitfield approach for numSV extraction from the new 0x83 block as a starting point. 
**This numSV decoding approach may not be correct, and more work needs to go into properly deciphering this block. This release is aimed at enabling users to track and recover these new RS41s so further analysis can be performed.**
> 1.8.1-beta6 - RS41 X-Series Preliminary Support

- Dockerfile
Changes to ka9q-radio's makefile mean that it now requires more dependencies to build the utilities that Auto-RX needs. Here I've added in more or less everything, except for `rsync`, which is only needed by the `install` target.
> Update to the latest ka9q-radio commit

- auto_rx/autorx/__init__.py
- demod/mod/m20mod.c
- demod/mod/rs41mod.c
- Updates to RS41 and M20 decoders from rs1729
- M20 Demodulator has better handling of some less common M20 serial numbers
- RS41 demod now uses an updated numSV count technique for the newer block format. numSV counts will be higher, as we are now expecting the sonde to be using multiple GNSS constellations.
- Recommended ka9q-radio commit is now 854ef7510a125a95312dabc285c1ba8371f675f2
> v1.8.1-beta7 - Rebase RS41 and M20 demodulators to rs1729 latest testing

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/templates/index.html
- auto_rx/station.cfg.example
- auto_rx/station.cfg.example.network
Add IMETWIDE sonde type, to allow users to force a wideband imet decoder to be started, either using the web interface, or the always_decode functions.
Note - I think i need to remove all the regular vs experimental decode chain business in decode.py. It's no longer required, and just serves to add confusion when adding decoder entreis.
> Add IMETWIDE sonde type

- Dockerfile
- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/scan.py
SDRs are no longer removed from the SDR list when using KA9Q-Radio or SpyServer. Instead, auto_rx will continue to retry connections forever, emitting error log messages. Behaviour for RTLSDRs should be unchanged.
auto_rx seems to recover OK, at least for KA9Q-radio. Untested for Spyserver.
Recommended ka9q-radio version is now 82e3f73f3bddb81740d0e4b22a1cb30dba46309e , as this correctly times out when samples stop being received.
> v1.8.2-beta3 Better handling of timeouts when using ka9q-radio and spyserver.

- auto_rx/autorx/__init__.py
- auto_rx/autorx/decode.py
RD41 decoder needed to have --softinv option used (based on a recording from an actual RD41). Still unsure how this will go in the wild, but let's see.
From some testing by Stefan HB9TMC, we're applying some tweaks to the RS41 fsk_demod parameters.
Previous settings (--mask=4800, with default oversampling setting of 10):
```
rs41_96k_float_07.5dB.bin, 0, 0.674
rs41_96k_float_08.0dB.bin, 0, 0.676
rs41_96k_float_08.5dB.bin, 0, 0.697
rs41_96k_float_09.0dB.bin, 3, 0.681
rs41_96k_float_09.5dB.bin, 54, 0.673
rs41_96k_float_10.0dB.bin, 103, 0.662
rs41_96k_float_10.5dB.bin, 115, 0.706
rs41_96k_float_11.0dB.bin, 110, 0.673
rs41_96k_float_11.5dB.bin, 116, 0.744
rs41_96k_float_12.0dB.bin, 118, 0.675
```
New settings (--mask=5000 --nsym=300 -p 5):
```
rs41_96k_float_07.0dB.bin, 0, 0.975 …
```
> v1.8.2-beta5 - Use inverted soft-in for RD91, tweak RS41 demod parameters.
