- auto_rx/auto_rx.py
- auto_rx/config_reader.py
- auto_rx/rotator_utils.py
- auto_rx/station.cfg.example
- New rotator_utils.py module, which handles comms with rotctld.
- Updated some default settings.
- Some re-structuring of the config file.
> Add support for communicating with Hamlib's rotctld.

- README.md
- auto_rx/README.md
- auto_rx/auto_rx.service
Move documentation to the wiki.
> Documentation Updates

- auto_rx/build.sh
- demod/demod.c
- demod/demod.h
- demod/demod_dft.c
- demod/demod_dft.h
- demod/dfm09dm.c
- demod/rs41dm.c
- demod/rs41dm_dft.c
- demod/rs92dm.c
Pulled in latest rs1729 changes, updated to print JSON and updated build script to build new version.
Tested with .wav files. Need to test with real world sondes tonight.
Fixes #7
> Upgrade binaries to new rsdemod variety

- auto_rx/auto_rx.py
- auto_rx/config_reader.py
- auto_rx/station.cfg.example
- Add a config file option (on by default) to produce a per-sonde log file in ./log/.
- Add a command-line option to allow supplying a custom ephemeris file, instead of downloading one.
> Added option for per-sonde log file (on by default).

- auto_rx/auto_rx.py
- auto_rx/habitat_utils.py
NOTE: This change will require a new payload doc to be created on Habitat.
> Fixed greylist functionality, added Habitat telemetry comment field.

- auto_rx/auto_rx.py
- demod/rs92dm.c
Tested with samples. Not sure when next ozone launch is so might be awhile before properly tested
> add aux data to rs92

- auto_rx/auto_rx.py
Probably not the cleanest way of doing this, but it works...
> Add ozone sonde indication to all outputs.

- auto_rx/auto_rx.py
- auto_rx/utils/log_to_kml.py
- Add either _system or _sonde to the log files that are written.
- Added log_to_kml.py within utils/. This utility will parse one or many log files, and convert to a KML file. The various functions within this file could be re-used for other endeavours, such as a live-KML output module.
> Log Filename Changes + KML Utils

- auto_rx/auto_rx.py
- auto_rx/habitat_utils.py
Significant robustness improvements to the Habitat uploader. It will now auto-retry on a HTTP code 409 error, and will handle upload timeouts a bit more gracefully.
> Habitat Upload Behaviour Updates

- auto_rx/auto_rx.py
- auto_rx/build.sh
- auto_rx/utils/receiver_stats.py
- demod/demod_dft.c
- demod/demod_dft.h
- demod/dfm09dm_dft.c
- demod/m10dm_dft.c
- demod/rs41dm.c
- demod/rs41dm_dft.c
- demod/rs92dm_dft.c
- Update to the latest demod code from the upstream RS repository.
- Add better handling of radiosonde detections.
- Add support for Graw DFM06 / DFM09 Radiosondes. (Noting that only a DFM09 sonde has been tested)
> Add DFM06/DFM09 support.

- auto_rx/auto_rx.py
- auto_rx/autorx/config.py
- auto_rx/autorx/email_notification.py
- auto_rx/station.cfg.example
Sends an email when a new sonde is detected, with some basic details and a link to habhub.
> Add email notification function

- auto_rx/autorx/email_notification.py
I forgot to include a date field.
> Include a timestamp in emails

- README.md
- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/static/js/utils.js
- auto_rx/autorx/templates/index.html
- auto_rx/autorx/utils.py
- auto_rx/autorx/web.py
- Add the ability to show azimuth/elevation/range data, if the station lat/lon is provided.
- Add a line-of-sight path line, like on tracker.habhub.org
- Add age field (this is a bit hacky, I have to update the entire table every second for this to work.. doesn't appear to add much overhead)
- Reverse ordering on log table, so newest log entries appear at top.
- Add "Hide map" button, and move hide map/scan plot buttons *above* their respective divs.
> Add az/el/range calculation, and LOS bearing on map.

- README.md
- auto_rx/README.md
- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/config.py
- auto_rx/station.cfg.example
- Update the APRS uploader to be somewhat more compliant with the APRS spec (and work with radiosondy.info)
- Add the ability to upload a station position beacon to APRS-IS.
- Some restructuring of the station.cfg example.
- Add link to ChaseMapper to the readme.
> APRS Updates

- auto_rx/auto_rx.py
As discussed in  #105 I have implemented the option to configure the log folder in the command line interface.
> Implemented command line argument log folder

- auto_rx/autorx/habitat.py
> Add version to user agent and print error messages on sondehub upload

- demod/rs41dm_dft.c
#119 Changes to rs41dm_dft.c for adding AUX output into autorx
> add aux output into json

- demod/demod_dft.c
- demod/demod_dft.h
- demod/demod_iq.c
- demod/demod_iq.h
- demod/dfm09dm_dft.c
- demod/lmsXdm_dft.c
- demod/m10dm_dft.c
- demod/rs41dm_dft.c
- demod/rs41dm_iq.c
- demod/rs92dm_dft.c
Note: this reverts the rs41dm_dft aux-data change.
No performance changes noted with these updates.
> Re-base to latest upstream demodulators 

- demod/rs41dm_dft.c
Fixes #119
Tested against ozonesonde sample and normal rs41 sample
> Minor tweaks to auxdata collection

- auto_rx/autorx/scan.py
This will resolve https://github.com/projecthorus/radiosonde_auto_rx/issues/97
> Add additional error output when running rtl_power.

- auto_rx/auto_rx.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/habitat.py
- auto_rx/autorx/logger.py
- auto_rx/station.cfg.example
- Added the ability for the user to define a 'station code', to add additional entropy to the iMet unique ID generation algorithm. This code is added to the comment field for Habitat uploads.
- Added a humidity field to the log file output.
> Additional changes for ongoing iMet support.

- auto_rx/autorx/__init__.py
- auto_rx/autorx/decode.py
Yet another example of why we need CI.
> Fix DFM, RS92 and M10 experimental demod chains.

- auto_rx/autorx/__init__.py
- auto_rx/autorx/geometry.py
- auto_rx/autorx/templates/index.html
- auto_rx/autorx/utils.py
- auto_rx/autorx/web.py
- auto_rx/utils/plot_sonde_log.py
This fixes:
https://github.com/projecthorus/radiosonde_auto_rx/issues/171
https://github.com/projecthorus/radiosonde_auto_rx/issues/155
> Reverse ordering of sondes in web GUI, add internal calculation of ascent/descent rates.

- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/sonde_specific.py
- auto_rx/autorx/utils.py
- auto_rx/build.sh
- auto_rx/station.cfg.example
- auto_rx/test/test_demod.py
- demod/mod/demod_mod.c
- demod/mod/demod_mod.h
- demod/mod/m10mod.c
- demod/mod/rs41mod.c
Also now use the -F9 option for the experimental demod chains, for better channel filtering.
> Switch to dfm09mod, report APRS station position using a position report.

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/ozimux.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/utils.py
- auto_rx/autorx/web.py
- auto_rx/build.sh
- auto_rx/station.cfg.example
- auto_rx/utils/compare_vaisala.py
- auto_rx/utils/plot_sonde_log.py
- mk2a/mk2a_lms1680.c
- scan/dft_detect.c
This is likely to only work when using a whitelist, or manually starting auto_rx.
This merge also adds a few config file options which tweak some scanning settings when scanning 1680 MHz sondes.
> Add initial MK2A (1680 MHz LMS6) Support.

- auto_rx/autorx/email_notification.py
Very important, please accept.
> Fix email notification layout

- auto_rx/autorx/__init__.py
- auto_rx/autorx/decode.py
This drops CPU usage by... a lot.
> Lower statistics output rate considerably.

- auto_rx/auto_rx.py
- auto_rx/autorx/config.py
- auto_rx/autorx/habitat.py
This feature will be used in future automated testing.
> Add habitat URL as a config option for use in testing

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/sonde_specific.py
- demod/mod/README.md
- demod/mod/dfm09mod.c
Changes to Graw DFM radiosonde callsign generation (Habitat and APRS).
Habitat callsign now: DFM-yynnnnnn
APRS callsign now: Dyynnnnnn
> DFM Callsign Changes

- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/habitat.py
- auto_rx/autorx/logger.py
- auto_rx/autorx/templates/index.html
- auto_rx/utils/listener_nmea_crlf.py
- demod/mod/dfm09mod.c
- demod/mod/m10mod.c
- Remove creation of Habitat payload documents (no longer required, as we use a common payload doc for all sondes now)
- Add Vertical/Horizontal velocity and hearing to log file.
- Add changes from @vg1320 for DFM and M10 demodulators (adds battery voltage output, additional PTU data for M10)
- Minor tweaks to web interface.
- Add UDP to NMEA script.
> Remove Habitat Payload Document Creation, other Updates

- README.md
- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/build.sh
- auto_rx/station.cfg.example
- demod/mod/dfm09mod.c
- demod/mod/m10mod.c
- demod/mod/mXXmod.c
WARNING: This makes some big changes to DFM frame IDs, which may cause interesting issues on the sondehub map when old & new stations upload positions for the same sonde.
> Persistent APRS, DFM Frame ID Changes

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/email_notification.py
- auto_rx/autorx/fsk_demod.py
- auto_rx/autorx/geometry.py
- auto_rx/autorx/gps.py
- auto_rx/autorx/gpsd.py
- auto_rx/autorx/habitat.py
- auto_rx/autorx/logger.py
- auto_rx/autorx/ozimux.py
- auto_rx/autorx/rotator.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/sonde_specific.py
- auto_rx/autorx/templates/index.html
- auto_rx/autorx/udplistener.py
- auto_rx/autorx/utils.py
- auto_rx/autorx/web.py
- auto_rx/station.cfg.example
Added the Live KML code from drid, then used black to fix formatting on all the python source... Resulting in this huge PR.
> Add Live KML, fix code formatting using black

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/email_notification.py
- auto_rx/station.cfg.example
Initial shot at landing notifications.
> Added email landing notifications

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/email_notification.py
- auto_rx/autorx/habitat.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/utils.py
- auto_rx/autorx/web.py
- auto_rx/build.sh
- demod/mod/imet54mod.c
Decoding working using IQ into RS decoder. iMet-54 will not be detected by scans so auto_rx will have to be started manually.
> iMet-54 Decoding

- auto_rx/autorx/static/css/tabulator_simple.css
- auto_rx/autorx/templates/index.html
Added a style for the lines to make the results easier to readthe
Added ability to sort by columns: SDR, Type, Freq, Time and Range.
> Quality of life changes

- README.md
- auto_rx/README.md
- auto_rx/autorx/__init__.py
- auto_rx/autorx/decode.py
- auto_rx/build.sh
- demod/mod/dfm09mod.c
- demod/mod/imet54mod.c
- demod/mod/lms6Xmod.c
- demod/mod/m10mod.c
- demod/mod/mXXmod.c
- demod/mod/meisei100mod.c
- demod/mod/rs41mod.c
- demod/mod/rs92mod.c
- imet/imet1rs_dft.c
- mk2a/mk2a_lms1680.c
This change ensures users run ./build.sh when they update. If they don't, the decoders will not work!
> Add version number in demods, add version check when running a decoder.

- auto_rx/autorx/__init__.py
- auto_rx/autorx/sondehub.py
... because I left this out accidentally!
> Sondehub Uploader RS92 support

- .github/workflows/container.yml
Should fix errors such as https://github.com/projecthorus/radiosonde_auto_rx/actions/runs/585121000.
> Actions: Checkout the repository seperately

- auto_rx/autorx/templates/index.html
> Change HTML to show sondehub cards link

- Dockerfile
Required for piwheels version of numpy.
> Docker: Install extra packages on armv6l and armv7l

- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/templates/index.html
Solves #442 
Please test and let me know what you think.
> Move current version information to homescreen

- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/templates/index.html
**This should not be merged yet.**
This is the style for the web interface, it works decently well with dark/light mode and desktop/mobile screens.
The buttons do nothing they need to be hooked up to the backend functions.
> Interface Design For Control Modal + Unread ERROR log notification

- README.md
- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/station.cfg.example
> Deprecate Habitat Uploader

- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/static/js/autorxapi.js
- auto_rx/autorx/templates/index.html
- Text in control modal now matches theme always
- viewheight now works better on mobile and desktop
- switch from cookies to localstorage
- password is stored in localstorage
- auto login if saved
- sidebar only red for error and critical logs
> Fixes for web and mobile

- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/static/js/autorxapi.js
- auto_rx/autorx/templates/index.html
I've implemented the changes discussed, buttons are disabled once the command has been executed until the current task is updated or 10s has elapsed whichever is first.t
> Control Buttons disable until ready to issue new command

- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/templates/index.html
Removed the double tooltip on the map and added additional data displayed in the tooltip, such as altitude, climb and horizontal speed.
A style has been added for the sondeTooltip class.
> Additional data displayed in the tooltip

- auto_rx/auto_rx.py
- auto_rx/autorx/config.py
- auto_rx/autorx/scan.py
- auto_rx/station.cfg.example
Renames scan lists to make them make more sense.
Black got a little eager on some things, I can unstage those if you want.
Closes #463
> Renames scan lists

- .devcontainer.json
- .gitignore
- Dockerfile.dev
Can also be used for local development without Visual Studio Code.
Updates to https://github.com/projecthorus/radiosonde_auto_rx/wiki/Development-&-Contributing incoming once this merges.
/cc @LukePrior @darksidelemm
> Visual Studio Code Dev Container

- auto_rx/autorx/templates/historical.html
This should be most of the fixes.
> Historical Page Styling & other changes

- auto_rx/autorx/templates/historical.html
I have added a new button to quickly log (straight line no burst) and the slow plot now initially uses quicklog before going back and updating each path.
> Use quicklog function for plotting

- auto_rx/autorx/log_files.py
- auto_rx/autorx/templates/historical.html
- auto_rx/autorx/web.py
Just don't look too closely at how i'm passing the selection to the backend.
> Add ability to download a selection of log files as a zip..

- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/templates/historical.html
Changes
Removed skew-t remove button
Rearranged button order
Removed autorx icon
Added decimation slider, slider value, and regenerate button (does not call any function)
> Historical page improvements

- auto_rx/autorx/templates/historical.html
Set span height so slider looks better
save decimation value as cookie for persistence
quick lines override works again
> Historical view fixes

- auto_rx/autorx/templates/historical.html
remove console logs
fix menu wait
> few final improvements

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/sonde_specific.py
- auto_rx/station.cfg.example
- mk2a/mk2a_lms1680.c
WARNING: The raw data logging (new save_raw_data option) has only been tested on RS41 sondes. It still needs to be tested on all the other sondes auto_rx supports. Let me know if you encounter issues!
> Relax Vaisala callsign regex, add option to log raw data to file.

- auto_rx/autorx/templates/historical.html
I have added a feature to plot landing that will generate a coverage polygon.
The feature runs into issues with complex edge cases and limited amounts of data.
> Initial polygon coverage feature

- auto_rx/autorx/templates/historical.html
I have made a few improvements to the code so hopefully, it all works a bit better now.
> Historical view, Plot launches button, fixes

- auto_rx/autorx/__init__.py
- auto_rx/autorx/log_files.py
- auto_rx/autorx/templates/historical.html
- auto_rx/autorx/utils.py
Testing out the addition of minimum height and maximum range data. Sidebar has been expanded slightly, and I've switched to a shortened form of the sonde type, with a tooltip showing the full type on hover-over.
> Tweaks to historical table

- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/utils.py
- auto_rx/build.sh
- auto_rx/clean.sh
- mk2a/mk2a1680mod.c
WARNING - This increases the CPU usage of the LMS6-1680 decoding chain by a fair bit.
It should be OK on a RPi 3 or better, but needs testing in the wild.
> LMS6-1680 Decoder Upgrades, Move APRS Object Name Generation

- .github/workflows/container.yml
- Dockerfile
- Dockerfile.dev
This should resolve the issues with `numpy` on the Raspberry Pi Zero W.
> Stop using piwheels

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/sdr_wrappers.py
- auto_rx/autorx/sondehub.py
- auto_rx/autorx/templates/index.html
- auto_rx/autorx/utils.py
- auto_rx/build.sh
- auto_rx/clean.sh
- auto_rx/station.cfg.example
- auto_rx/station.cfg.example.network
- auto_rx/test/plot_per.py
- auto_rx/test/test_demod.py
- demod/mod/dfm09mod.c
- demod/mod/imet54mod.c
- demod/mod/lms6Xmod.c
- demod/mod/mXXmod.c
- demod/mod/meisei100mod.c
- demod/mod/mp3h1mod.c
- demod/mod/rs41mod.c
- demod/mod/rs92mod.c
- imet/imet4iq.c
Heaps of changes in here...
- Rebased demodulators.
- Add SDR wrapper abstraction
- Add support for using spyserver_client
- Switched to using centred IQ for all demodulators
- iMet decoders now take IQ input
> v1.6.0 testing release

- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/templates/index.html
The changes concern the size of the sliders, the font and the arrangement of elements. By the way, I changed the way of displaying the date and time for the UTC format
> Minor changes to the display style of the log bars and settings

- auto_rx/autorx/__init__.py
- auto_rx/autorx/decode.py
Meisei decoder:
- 'Normal' -> IQ demod using zilog IQ demod.
- 'Experimental' -> IQ demod using fsk_demod
> 1.6.0-beta7 - Meisei fsk_demod attempt

- auto_rx/autorx/scan.py
- auto_rx/autorx/sdr_wrappers.py
Some SDRs have need this to avoid significat vallyes in the spectrum of the scan
> Increase the crop for rtl_power 20% -> 25%

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/aprs.py
- auto_rx/autorx/config.py
- auto_rx/autorx/email_notification.py
- auto_rx/autorx/habitat.py
- auto_rx/autorx/logger.py
- auto_rx/autorx/ozimux.py
- auto_rx/autorx/rotator.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/sondehub.py
- auto_rx/autorx/utils.py
- auto_rx/autorx/web.py
- auto_rx/test/bit_to_samples.py
- auto_rx/utils/listener_nmea_crlf.py
> Remove Python 2 compatibility hacks

- demod/mod/demod_mod.c
- demod/mod/demod_mod.h
- imet/imet4iq.c
- mk2a/mk2a1680mod.c
Backported from https://github.com/rs1729/RS
> Fix read_wav_header return value type

- .gitignore
- README.md
- demod/mod/mts01mod.c
I tested it with MTS01 probe and then I was able to see temperature value
Updated README file to enable temp on Meteosis MTS01
> Update mts01mod for hor.vel and temp

- auto_rx/autorx/log_files.py
- auto_rx/autorx/static/css/main.css
- auto_rx/autorx/templates/historical.html
- auto_rx/autorx/templates/index.html
I hoped to add a frequency column to the Sonde List same as #729.
So I made it based on a suggestion of the following comment.
https://github.com/projecthorus/radiosonde_auto_rx/issues/729#issuecomment-1362472187
I added a settings icon of Sonde List to the same position as "main" page.
I have one issue of a icon position of "return to main" and "SkewT".
I think that it is better that a icon position of "return to main" and "go to history" is same as current version.
So I swapped them.
Please check!
> Add a frequency column to the Sonde List and add a visibility setting of each column of it.

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/email_notification.py
- auto_rx/station.cfg.example
- auto_rx/station.cfg.example.network
- demod/mod/m20mod.c
M20 Battery voltage, email notifications for encrypted sonde detections.
> v1.6.2-beta1

- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/scan.py
- auto_rx/station.cfg.example
- auto_rx/station.cfg.example.network
Fix from @pasky here https://github.com/projecthorus/radiosonde_auto_rx/pull/777#issuecomment-1605427962
> Breakout of scan loop faster

- auto_rx/autorx/static/js/autorxapi.js
- auto_rx/autorx/static/js/utils.js
- auto_rx/autorx/templates/historical.html
- auto_rx/autorx/templates/index.html
- auto_rx/autorx/templates/skewt_test.html
- auto_rx/autorx/web.py
> Fix reverse proxy path handling

- .gitignore
- Makefile
- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/rotator.py
- auto_rx/autorx/scan.py
- auto_rx/autorx/sondehub.py
- auto_rx/autorx/templates/index.html
- auto_rx/autorx/utils.py
- auto_rx/autorx/web.py
- auto_rx/build.sh
- auto_rx/station.cfg.example
- auto_rx/station.cfg.example.network
- auto_rx/utils/plot_rtl_power.py
- scan/dft_detect.c
- weathex/Makefile
- weathex/weathex301d.c
This also has initial Weathex WXR-301D support, but this has not been tested at all, so will probably break somewhere. Awaiting arrival of a WxR-301D unit to test with.
> Merge in some temporary fixes.

- auto_rx/auto_rx.py
- auto_rx/autorx/__init__.py
- auto_rx/autorx/config.py
- auto_rx/autorx/decode.py
- auto_rx/autorx/logger.py
- auto_rx/autorx/sondehub.py
- auto_rx/autorx/templates/index.html
- auto_rx/station.cfg.example
- auto_rx/station.cfg.example.network
- demod/mod/rs41mod.c
... and optionally save it to disk.
> Mainboard type on web interface, upload RS41 subframe data to SondeHub

- auto_rx/autorx/__init__.py
- demod/mod/m20mod.c
Possible fix to M20 with aux data issue.
> Rebase m20mod.c

- auto_rx/autorx/__init__.py
- auto_rx/station.cfg.example
- auto_rx/station.cfg.example.network
- demod/mod/dfm09mod.c
Going to have to bring these changes over to the master branch and do a 1.7.3 release I think...
> 1.7.3-beta10 - Rebase dfm demodulator for better DFM17 handling

- .devcontainer.json
- .github/workflows/container.yml
- Dockerfile
- auto_rx/autorx/__init__.py
Requires testing on the numerous platforms before being released beyond `testing`.
> Upgrade container image to bookworm and overhaul actions workflow

- auto_rx/autorx/__init__.py
- auto_rx/autorx/ozimux.py
... also bump beta version since there's been a heap of changes.
> Send pressure and aux data in payload summary message

- Dockerfile
- auto_rx/autorx/__init__.py
- auto_rx/autorx/templates/index.html
For the crazies that have nothing better to do than build receivers.
> Add "All" option to pagination size dropdown
